#!/bin/bash
# wget -O - https://get.hacs.xyz | bash -

function run() {
    set -e

    RED_COLOR='\033[0;31m'
    GREEN_COLOR='\033[0;32m'
    GREEN_YELLOW='\033[1;33m'
    NO_COLOR='\033[0m'

    declare haPath
    declare -a paths=(
        "$PWD"
        "$PWD/config"
        "/config"
        "/homeassistant"
        "$HOME/.homeassistant"
        "/usr/share/hassio/homeassistant"
    )

    function info () { echo -e "${GREEN_COLOR}INFO: $1${NO_COLOR}";}
    function warn () { echo -e "${GREEN_YELLOW}WARN: $1${NO_COLOR}";}
    function error () { echo -e "${RED_COLOR}ERROR: $1${NO_COLOR}"; if [ "$2" != "false" ]; then exit 1;fi; }

    function checkRequirement () {
        if [ -z "$(command -v "$1")" ]; then
            error "'$1' is not installed"
        fi
    }

    checkRequirement "wget"
    checkRequirement "unzip"

    info "Trying to find the correct directory..."
    for path in "${paths[@]}"; do
        if [ -n "$haPath" ]; then
            break
        fi

        if [ -f "$path/.HA_VERSION" ]; then
            haPath="$path"
        fi
    done

    if [ -n "$haPath" ]; then
        info "Found Home Assistant configuration directory at '$haPath'"
        cd "$haPath" || error "Could not change path to $haPath"
        if [ ! -d "$haPath/custom_components" ]; then
            info "Creating custom_components directory..."
            mkdir "$haPath/custom_components"
        fi

        info "Changing to the custom_components directory..."
        cd "$haPath/custom_components" || error "Could not change path to $haPath/custom_components"

        info "Downloading HACS Proxy"
        rm -f "$haPath/custom_components/hacs_proxy.zip"
        wget "https://github.com/ryanh7/hacs-proxy/releases/latest/download/hacs_proxy.zip"

        if [ -d "$haPath/custom_components/hacs_proxy" ]; then
            warn "HACS_Proxy directory already exist, cleaning up..."
            rm -R "$haPath/custom_components/hacs_proxy"
        fi

        info "Creating HACS_Proxy directory..."
        mkdir "$haPath/custom_components/hacs_proxy"

        info "Unpacking HACS_Proxy..."
        unzip "$haPath/custom_components/hacs_proxy.zip" -d "$haPath/custom_components/hacs_proxy" >/dev/null 2>&1

        echo
        info "Removing HACS_Proxy zip file..."
        rm -f "$haPath/custom_components/hacs_proxy.zip"
        info "Installation complete."
        echo
        info "Remember to restart Home Assistant before you configure it"

    else
        echo
        error "Could not find the directory for Home Assistant" false
        echo "Manually change the directory to the root of your Home Assistant configuration"
        echo "With the user that is running Home Assistant"
        echo "and run the script again"
        exit 1
    fi
}