name: zip and release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP
        run: |
          mkdir -p output
          cd custom_components/hacs_proxy
          zip -r ../../output/hacs_proxy.zip *

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hacs_proxy_zip
          path: output/hacs_proxy.zip

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: output/hacs_proxy.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
